import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi'
import { getFxRate } from './service'

// This type is generated by `wrangler types`
type Env = {
  KV_CACHE: KVNamespace
}

const fxRateSchema = createRoute({
  method: 'get',
  path: '/',
  operationId: 'getFxRate',
  responses: {
    200: {
      description: 'Current SGD to USD exchange rate',
      content: {
        'application/json': {
          schema: z.object({
            rate: z.number(),
            source: z.enum(['cache', 'api', 'fallback']),
          }),
        },
      },
    },
  },
  tags: ['Currency'],
})

export const fxApi = new OpenAPIHono<{ Bindings: Env }>()

fxApi.openapi(fxRateSchema, async (c) => {
  try {
    const result = await getFxRate(c.env)
    return c.json(result, 200)
  } catch (error) {
    console.error('FX Rate Error:', error)
    return c.json(
      { rate: 0.74, source: 'fallback' as const },
      200
    )
  }
})
