import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi';
import { callGeminiApi } from '../../../src/lib/gemini'; // Adjusted import path

// This type is generated by `wrangler types`
type Env = {
  GEMINI_API_KEY: string;
  // Add other env vars if needed by callGeminiApi
};

const chatSchema = createRoute({
  method: 'post',
  path: '/',
  operationId: 'postChat',
  request: {
    body: {
      content: {
        'application/json': {
          schema: z.object({
            // For simplicity, we'll take the last user message as the prompt
            messages: z.array(z.object({
              role: z.enum(['user', 'assistant']),
              content: z.string(),
            })),
            model: z.string().optional().default('gemini-1.5-flash'),
          }),
        },
      },
    },
  },
  responses: {
    200: {
      description: 'AI chat response',
      content: {
        'application/json': {
          // The response structure from callGeminiApi can be defined here
          schema: z.any(),
        },
      },
    },
    500: {
      description: 'Error response',
      content: {
        'application/json': {
          schema: z.object({ error: z.string() }),
        },
      },
    }
  },
});

export const chatApi = new OpenAPIHono<{ Bindings: Env }>();

chatApi.openapi(chatSchema, async (c) => {
  const { messages, model } = await c.req.json();

  const lastUserMessage = messages.filter(m => m.role === 'user').pop();

  if (!lastUserMessage) {
    return c.json({ error: 'No user message found' }, 400);
  }

  try {
    const response = await callGeminiApi(c.env, model, lastUserMessage.content);
    return c.json(response);
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
    return c.json({ error: `Failed to get response from AI: ${errorMessage}` }, 500);
  }
});