import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi'
import { streamText } from 'ai'
import { createGoogleGenerativeAI } from '@ai-sdk/google'

// This type is generated by `wrangler types`
type Env = {
  GEMINI_API_KEY: string
}

const chatSchema = createRoute({
  method: 'post',
  path: '/',
  operationId: 'postChat',
  request: {
    body: {
      content: {
        'application/json': {
          schema: z.object({
            messages: z.array(z.object({
              role: z.enum(['user', 'assistant']),
              content: z.string(),
            })),
          }),
        },
      },
    },
  },
  responses: {
    200: {
      description: 'AI chat response stream',
      content: {
        'text/event-stream': {
          schema: z.string(),
        },
      },
    },
  },
})

export const chatApi = new OpenAPIHono<{ Bindings: Env }>()

chatApi.openapi(chatSchema, async (c) => {
  const { messages } = await c.req.json()

  if (!c.env.GEMINI_API_KEY) {
    return c.json({ error: 'GEMINI_API_KEY is not set' }, 500)
  }

  const google = createGoogleGenerativeAI({
    apiKey: c.env.GEMINI_API_KEY,
  })

  const result = await streamText({
    model: google('models/gemini-1.5-flash-latest'),
    messages,
  })

  return result.toResponse()
})
