// This type is generated by `wrangler types`
type Env = {
  // ... any bindings needed inside the DO
}

export class WebSocketServer implements DurableObject {
  state: DurableObjectState
  env: Env
  sessions: WebSocket[] = []

  constructor(state: DurableObjectState, env: Env) {
    this.state = state
    this.env = env
    this.sessions = []
  }

  broadcast(message: string) {
    this.sessions = this.sessions.filter(session => {
      try {
        session.send(message)
        return session.readyState === WebSocket.OPEN
      } catch (err) {
        return false
      }
    })
  }

  async fetch(request: Request) {
    const upgradeHeader = request.headers.get('Upgrade')
    if (upgradeHeader !== 'websocket') {
      return new Response('Expected WebSocket upgrade', { status: 426 })
    }

    const [client, server] = Object.values(new WebSocketPair())
    server.accept()
    this.sessions.push(server)

    server.addEventListener('message', (event) => {
      console.log('DO received message:', event.data)
      this.broadcast(JSON.stringify({
        type: 'message',
        data: `Echo: ${event.data}`,
      }))
    })

    server.addEventListener('close', () => {
      this.sessions = this.sessions.filter(s => s !== server)
      this.broadcast(JSON.stringify({ type: 'status', data: 'A user disconnected' }))
    })

    server.addEventListener('error', (err) => {
      console.error('DO WebSocket error:', err)
    })

    return new Response(null, {
      status: 101,
      webSocket: client,
    })
  }
}
