import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi'
import { runAllHealthChecks } from './service'

// This type is generated by `wrangler types`
type Env = {
  DB: D1Database
  AI: Ai
}

const healthSchema = createRoute({
  method: 'get',
  path: '/',
  operationId: 'getHealth',
  responses: {
    200: {
      description: 'System health status',
      content: {
        'application/json': {
          schema: z.object({
            overallStatus: z.enum(['PASS', 'FAIL']),
            checks: z.array(z.object({
              name: z.string(),
              status: z.enum(['PASS', 'FAIL']),
              log: z.string().optional(),
            })),
          }),
        },
      },
    },
  },
})

export const healthApi = new OpenAPIHono<{ Bindings: Env }>()

healthApi.openapi(healthSchema, async (c) => {
  const healthResults = await runAllHealthChecks(c.env.DB, c.env.AI)
  const status = healthResults.overallStatus === 'FAIL' ? 503 : 200
  return c.json(healthResults, status)
})
