import { OpenAPIHono } from '@hono/zod-openapi'
import { chatApi } from './modules/chat'
import { healthApi } from './modules/health'
import { productsApi } from './modules/dummyjson'
import { createOpenApiSpec } from './utils/openapi'
import { WebSocketServer } from './do/websocket'
import { mcpAgent } from './modules/mcp'
import { AdvisorAgent } from '../src/agent'
import { MarketScanWorkflow } from '../src/workflow'

/**
 * Environment bindings for the Cloudflare Worker
 * This type is generated by `wrangler types` command
 *
 * Includes bindings for:
 * - AI: Cloudflare Workers AI
 * - DB: D1 Database
 * - WS_HANDLER: WebSocket Durable Object
 * - ASSETS: Static asset serving
 * - MCP authentication settings (optional)
 */
type Env = {
  AI: Ai
  DB: D1Database
  WS_HANDLER: DurableObjectNamespace<WebSocketServer>
  GEMINI_API_KEY: string
  ASSETS: Fetcher
  // MCP authentication settings (optional)
  // Enable these in wrangler.toml for production
  MCP_AUTH_ENABLED?: string
  MCP_API_KEYS?: string // Comma-separated list of valid API keys
  CLOUDFLARE_ACCESS_TEAM_DOMAIN?: string
  CLOUDFLARE_ACCESS_AUDIENCE?: string
}

/**
 * Initialize the OpenAPI Hono application
 * This handles all API routes and serves the SPA
 */
const app = new OpenAPIHono<{ Bindings: Env }>()

/**
 * Mount modular API routes
 * Each module exports a Hono app that is mounted here
 */
app.route('/api/chat', chatApi)
app.route('/api/health', healthApi)
app.route('/api/products', productsApi)

/**
 * WebSocket Endpoint
 * Upgrades HTTP connections to WebSocket for real-time communication
 * Uses Durable Objects for stateful WebSocket management
 */
app.get('/api/ws', async (c) => {
  const upgradeHeader = c.req.header('Upgrade')
  if (upgradeHeader !== 'websocket') {
    return c.json({ error: 'Expected WebSocket upgrade' }, 426)
  }
  const id = c.env.WS_HANDLER.idFromName('default-room')
  const stub = c.env.WS_HANDLER.get(id)
  return stub.fetch(c.req.raw)
})

/**
 * OpenAPI Specification Endpoint
 * Auto-generates OpenAPI documentation from Hono routes
 * Access at: /api/openapi.json
 */
app.doc('/api/openapi.json', createOpenApiSpec(app))

/**
 * Main Worker fetch handler
 *
 * Routes requests to:
 * 1. MCP endpoints (/mcp, /sse) - Model Context Protocol server
 * 2. API routes (/api/*) - REST API endpoints
 * 3. Static assets - SPA (Single Page Application)
 *
 * MCP endpoints are handled separately to avoid Hono middleware conflicts
 * and to support both SSE and Streamable HTTP transports
 */
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url)
    const { pathname } = url

    // ============================================================================
    // MCP (Model Context Protocol) Endpoints
    // ============================================================================
    // These endpoints expose AI tools to MCP clients like Claude Desktop
    // Supports both legacy (SSE) and modern (Streamable HTTP) transports
    // Authentication is configured via environment variables

    /**
     * SSE Transport Endpoint: /sse
     *
     * Server-Sent Events transport for MCP (legacy)
     * - Original MCP transport protocol
     * - One-way streaming from server to client
     * - Backward compatible with older MCP clients
     *
     * @see https://developers.cloudflare.com/agents/model-context-protocol/transport/
     */
    if (pathname.startsWith('/sse')) {
      try {
        // Route to the SSE transport handler
        // The McpAgent handles all MCP protocol details
        const mcpHandler = mcpAgent.serveSSE('/sse')
        return mcpHandler.fetch(request, env, ctx)
      } catch (error) {
        // Log and return sanitized error response
        console.error('MCP SSE Error:', error)
        return new Response(
          JSON.stringify({
            error: 'Internal Server Error',
            message: error instanceof Error ? error.message : 'Unknown error',
          }),
          {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
          }
        )
      }
    }

    /**
     * Streamable HTTP Transport Endpoint: /mcp
     *
     * Streamable HTTP transport for MCP (recommended)
     * - Modern, simplified protocol
     * - Single endpoint for bi-directional communication
     * - Automatic protocol negotiation
     * - Supports both immediate responses and streaming
     * - Better error handling and performance
     *
     * @see https://developers.cloudflare.com/agents/model-context-protocol/transport/
     */
    if (pathname.startsWith('/mcp')) {
      try {
        // Route to the Streamable HTTP transport handler
        // This is the recommended transport for new MCP clients
        const mcpHandler = mcpAgent.serve('/mcp')
        return mcpHandler.fetch(request, env, ctx)
      } catch (error) {
        // Log and return sanitized error response
        console.error('MCP HTTP Error:', error)
        return new Response(
          JSON.stringify({
            error: 'Internal Server Error',
            message: error instanceof Error ? error.message : 'Unknown error',
          }),
          {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
          }
        )
      }
    }

    // ============================================================================
    // Standard Application Routes
    // ============================================================================
    // All non-MCP routes are handled by Hono
    // - API routes: /api/*
    // - Static assets: Served from ASSETS binding
    // - SPA: React application with client-side routing
    return app.fetch(request, env, ctx)
  },
}

// ============================================================================
// Durable Object Exports
// ============================================================================
// These exports make Durable Objects available to the Worker runtime

/**
 * WebSocket Durable Object
 * Manages stateful WebSocket connections for real-time features
 */
export { WebSocketServer }

/**
 * MCP Agent Durable Object
 * Manages stateful MCP sessions with persistent storage
 * Each MCP client gets its own isolated agent instance
 *
 * Required by the Cloudflare Agents SDK
 * Must match the class_name in wrangler.toml migrations
 */
export { mcpAgent as CloudflareMcpAgent }

export { AdvisorAgent }

export { MarketScanWorkflow }
